BERT Trn1, G5, G6 compatability
aws-samples/scalable-hw-agnostic-inference pull request #21
Opened 2024-10-03 15:58 UTC by jonrwong-amazon

*Issue #, if available:*

*Description of changes:*
Updated run-bert.py to work with GPU. Added trn1, g5, g6 associated YAML files as well

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-11 17:21 UTC, yahavb requested changes
left few comments. Need to remove unnecessary files. Improve naming and few more nits.

2024-10-11 17:21 UTC, yahavb commented on app/run-llama.sh
can we flip it? aarch64 is a cpu?

2024-10-11 17:21 UTC, yahavb commented on bert-c7g/bert-cpu-ing.yaml
we don't need to couple ingress with specific cpu types

2024-10-11 17:21 UTC, yahavb commented on bert-g5/bert-gpu-ing-2.yaml
what's that?

2024-10-11 17:21 UTC, yahavb commented on bert-g5/bert-gpu-svc-2.yaml
same here

2024-10-11 17:21 UTC, yahavb commented on bert-m8g/bert-gp-deploy.yaml
what's that?

2024-10-11 17:21 UTC, yahavb commented on bert-m8g/bert-gp-ing.yaml
what's bertgp?

2024-10-11 17:21 UTC, yahavb commented on mistral-g5/mistral-gpu-ing-2.yaml
can we have single ingress for model and use meaningful names other than mistralgpu-2

2024-10-11 17:21 UTC, yahavb commented on mistral-generalpurpose/mistral-gp-deploy.yaml
same here `mistral-gp`

2024-10-11 17:21 UTC, yahavb commented on nodepools/amd-g5-nodepool.yaml
is there a reason for specifying the instance size? We are specifying resources.limits and resources.requests. we need to allow karpenter do its thing rather than limiting it.

2024-10-11 17:21 UTC, yahavb commented on serving-container-build/README.md
can we just write $TO_BE_REPLACED instead of yahavb or jonrwong-amazon that can causes pulling code from the wrong git repo.

2024-10-11 18:11 UTC, jonrwong-amazon commented on bert-m8g/bert-gp-deploy.yaml
gp is short for general purpose

2024-10-11 18:12 UTC, jonrwong-amazon commented on bert-m8g/bert-gp-ing.yaml
it's short for bert general purpose, we can add it in the readme to explain it

2024-10-11 18:14 UTC, jonrwong-amazon commented on mistral-g5/mistral-gpu-ing-2.yaml
i can change the names to be more accurate

2024-10-11 18:14 UTC, jonrwong-amazon commented on mistral-generalpurpose/mistral-gp-deploy.yaml
gp is short for general purpose, we can add that into readme for clarity

2024-10-11 18:14 UTC, jdwisman commented on mistral-g5/mistral-gpu-ing-2.yaml
each model needs its own ingress because they have different target groups (G5 for one, G6 for the other).  But I agree with you on changing the name to something meaningful, mistralgpu-g5 and mistralgpu-g6 would be better.

2024-10-11 18:14 UTC, jonrwong-amazon commented on nodepools/amd-g5-nodepool.yaml
sure makes sense, will delete instance-size

2024-10-11 18:21 UTC, jdwisman commented on app/run-llama.sh
I think we should leave this because it specifies Graviton without GPU and not Graviton with GPU.

2024-10-17 18:48 UTC, jonrwong-amazon commented on serving-container-build/README.md
Yes, renamed it to be that variable

2024-10-17 19:09 UTC, yahavb commented
can we please break it to smaller PRs. I still looking for the issues I requested to be fixed.

2024-10-17 19:09 UTC, closed without merging